### ISSUE TITLE
Fix CSS and Responsiveness

### ISSUE THREAD

**Issue by mjgiannelli** [mjgiannelli/challenge-6-weather-dashboard#12]
Removed bootstrap and built css from scratch. Fix to get the website to look like the mock up and finalize responsiveness

**Comment by hamzaakif** [comment]
Hey, where can I find the mock up which you want your website to look like?

**Comment by mjgiannelli** [comment]
> Hey, where can I find the mock up which you want your website to look like? 

> Thank you for your question and interest in helping. This is for a school project so unfortunately I cannot get any outside help. Maybe we can collab on something in the future 😁

**Comment by hamzaakif** [comment]
> > Hey, where can I find the mock up which you want your website to look like?
> 
> > Thank you for your question and interest in helping. This is for a school project so unfortunately I cannot get any outside help. Maybe we can collab on something in the future 😁

Sure thing ! Actually I was learning to contribute to open source projects and saw your repo listed as open issue.

**Comment by mjgiannelli** [comment]
completed
